"""KPI Engine for computing revenue, profit, margins, growth, and orders."""

from __future__ import annotations

from typing import Any
import pandas as pd

REQUIRED_KPI_COLUMNS = ["Revenue", "Profit", "Order_ID", "Customer_ID"]

KPI_DEFINITIONS = [
    {
        "KPI": "Revenue",
        "Formula": "Sum of Revenue",
        "Business Meaning": "Total sales generated.",
    },
    {
        "KPI": "Profit",
        "Formula": "Sum of Profit",
        "Business Meaning": "Money remaining after costs.",
    },
    {
        "KPI": "Profit Margin",
        "Formula": "(Profit / Revenue) x 100",
        "Business Meaning": "Profit earned per 100 units of revenue.",
    },
    {
        "KPI": "Average Order Value",
        "Formula": "Revenue / Unique Orders",
        "Business Meaning": "Average revenue generated by one order.",
    },
    {
        "KPI": "Orders",
        "Formula": "Count of Unique Order_ID",
        "Business Meaning": "Number of distinct orders.",
    },
    {
        "KPI": "Customers",
        "Formula": "Count of Unique Customer_ID",
        "Business Meaning": "Number of distinct customers.",
    },
    {
        "KPI": "Monthly Growth Rate",
        "Formula": "((Latest Month Revenue - Previous Month Revenue) / Previous Month Revenue) x 100",
        "Business Meaning": "Revenue change between the latest two months.",
    },
]

def validate_kpi_columns(data: pd.DataFrame) -> None:
    missing = [col for col in REQUIRED_KPI_COLUMNS if col not in data.columns]
    if missing:
        raise ValueError("KPI calculations require these missing columns: " + ", ".join(missing))

def calculate_revenue(data: pd.DataFrame) -> float:
    return float(data["Revenue"].sum())

def calculate_profit(data: pd.DataFrame) -> float:
    return float(data["Profit"].sum())

def calculate_profit_margin(data: pd.DataFrame) -> float | None:
    rev = calculate_revenue(data)
    if rev == 0:
        return None
    return (calculate_profit(data) / rev) * 100

def _count_distinct_known(series: pd.Series) -> int:
    known = series.dropna().astype("string").str.strip()
    known = known[known.str.lower() != "unknown"]
    return int(known.nunique())

def calculate_orders(data: pd.DataFrame) -> int:
    return _count_distinct_known(data["Order_ID"])

def calculate_customers(data: pd.DataFrame) -> int:
    return _count_distinct_known(data["Customer_ID"])

def calculate_average_order_value(data: pd.DataFrame) -> float | None:
    orders = calculate_orders(data)
    if orders == 0:
        return None
    return calculate_revenue(data) / orders

def calculate_monthly_growth(data: pd.DataFrame) -> dict[str, Any]:
    """Compare revenue for the latest two calendar months."""
    if "Date" not in data.columns:
        return {
            "growth_rate": None,
            "current_period": None,
            "previous_period": None,
            "current_revenue": None,
            "previous_revenue": None,
        }

    dated = data.dropna(subset=["Date"]).copy()
    if dated.empty:
        return {
            "growth_rate": None,
            "current_period": None,
            "previous_period": None,
            "current_revenue": None,
            "previous_revenue": None,
        }

    dated["Month"] = dated["Date"].dt.to_period("M")
    monthly_rev = dated.groupby("Month")["Revenue"].sum().sort_index()

    if len(monthly_rev) < 2:
        return {
            "growth_rate": None,
            "current_period": str(monthly_rev.index[-1]),
            "previous_period": None,
            "current_revenue": float(monthly_rev.iloc[-1]),
            "previous_revenue": None,
        }

    curr_p = monthly_rev.index[-1]
    prev_p = monthly_rev.index[-2]
    curr_rev = float(monthly_rev.iloc[-1])
    prev_rev = float(monthly_rev.iloc[-2])
    
    growth = None if prev_rev == 0 else ((curr_rev - prev_rev) / prev_rev) * 100

    return {
        "growth_rate": growth,
        "current_period": str(curr_p),
        "previous_period": str(prev_p),
        "current_revenue": curr_rev,
        "previous_revenue": prev_rev,
    }

def calculate_kpis(data: pd.DataFrame) -> dict[str, Any]:
    if data.empty:
        raise ValueError("KPI calculations require at least one cleaned sales row.")

    validate_kpi_columns(data)
    growth = calculate_monthly_growth(data)
    return {
        "revenue": calculate_revenue(data),
        "profit": calculate_profit(data),
        "profit_margin": calculate_profit_margin(data),
        "average_order_value": calculate_average_order_value(data),
        "orders": calculate_orders(data),
        "customers": calculate_customers(data),
        "growth_rate": growth["growth_rate"],
        "growth_current_period": growth["current_period"],
        "growth_previous_period": growth["previous_period"],
        "growth_current_revenue": growth["current_revenue"],
        "growth_previous_revenue": growth["previous_revenue"],
    }

def kpis_to_dataframe(kpis: dict[str, Any]) -> pd.DataFrame:
    rows = [
        {"KPI": "Revenue", "Value": kpis["revenue"], "Unit": "currency"},
        {"KPI": "Profit", "Value": kpis["profit"], "Unit": "currency"},
        {"KPI": "Profit Margin", "Value": kpis["profit_margin"], "Unit": "percent"},
        {"KPI": "Average Order Value", "Value": kpis["average_order_value"], "Unit": "currency"},
        {"KPI": "Orders", "Value": kpis["orders"], "Unit": "count"},
        {"KPI": "Customers", "Value": kpis["customers"], "Unit": "count"},
        {"KPI": "Monthly Growth Rate", "Value": kpis["growth_rate"], "Unit": "percent"},
    ]
    return pd.DataFrame(rows)
