"""Reusable KPI calculations for cleaned sales data."""

from __future__ import annotations

from typing import Any

import pandas as pd


REQUIRED_KPI_COLUMNS = ["Revenue", "Profit", "Order_ID", "Customer_ID"]

KPI_DEFINITIONS = [
    {
        "KPI": "Revenue",
        "Formula": "Sum of Revenue",
        "Business Meaning": "Total sales value generated.",
    },
    {
        "KPI": "Profit",
        "Formula": "Sum of Profit",
        "Business Meaning": "Money remaining after costs.",
    },
    {
        "KPI": "Profit Margin",
        "Formula": "(Profit / Revenue) x 100",
        "Business Meaning": "Profit earned for every 100 units of revenue.",
    },
    {
        "KPI": "Average Order Value",
        "Formula": "Revenue / Unique Orders",
        "Business Meaning": "Average revenue generated by one order.",
    },
    {
        "KPI": "Orders",
        "Formula": "Count of Unique Order_ID",
        "Business Meaning": "Number of distinct orders.",
    },
    {
        "KPI": "Customers",
        "Formula": "Count of Unique Customer_ID",
        "Business Meaning": "Number of distinct customers.",
    },
    {
        "KPI": "Monthly Growth Rate",
        "Formula": "((Latest Month Revenue - Previous Month Revenue) / Previous Month Revenue) x 100",
        "Business Meaning": "Revenue change between the latest two months in the data.",
    },
]


def validate_kpi_columns(data: pd.DataFrame) -> None:
    """Raise a clear error when columns needed for core KPIs are unavailable."""
    missing = [column for column in REQUIRED_KPI_COLUMNS if column not in data.columns]
    if missing:
        raise ValueError(
            "KPI calculations require these missing column(s): " + ", ".join(missing)
        )


def calculate_revenue(data: pd.DataFrame) -> float:
    """Return total revenue."""
    return float(data["Revenue"].sum())


def calculate_profit(data: pd.DataFrame) -> float:
    """Return total profit."""
    return float(data["Profit"].sum())


def calculate_profit_margin(data: pd.DataFrame) -> float | None:
    """Return profit as a percentage of revenue."""
    revenue = calculate_revenue(data)
    if revenue == 0:
        return None
    return (calculate_profit(data) / revenue) * 100


def _count_distinct_known(series: pd.Series) -> int:
    """Count distinct IDs while excluding missing-value placeholders."""
    known_values = series.dropna().astype("string").str.strip()
    known_values = known_values[known_values.str.lower() != "unknown"]
    return int(known_values.nunique())


def calculate_orders(data: pd.DataFrame) -> int:
    """Return the number of distinct orders."""
    return _count_distinct_known(data["Order_ID"])


def calculate_customers(data: pd.DataFrame) -> int:
    """Return the number of distinct customers."""
    return _count_distinct_known(data["Customer_ID"])


def calculate_average_order_value(data: pd.DataFrame) -> float | None:
    """Return revenue divided by distinct orders."""
    orders = calculate_orders(data)
    if orders == 0:
        return None
    return calculate_revenue(data) / orders


def calculate_monthly_growth(data: pd.DataFrame) -> dict[str, Any]:
    """Compare revenue for the latest two calendar months in the data."""
    if "Date" not in data.columns:
        return {
            "growth_rate": None,
            "current_period": None,
            "previous_period": None,
            "current_revenue": None,
            "previous_revenue": None,
        }

    dated_data = data.dropna(subset=["Date"]).copy()
    if dated_data.empty:
        return {
            "growth_rate": None,
            "current_period": None,
            "previous_period": None,
            "current_revenue": None,
            "previous_revenue": None,
        }

    dated_data["Month"] = dated_data["Date"].dt.to_period("M")
    monthly_revenue = dated_data.groupby("Month")["Revenue"].sum().sort_index()

    if len(monthly_revenue) < 2:
        return {
            "growth_rate": None,
            "current_period": str(monthly_revenue.index[-1]),
            "previous_period": None,
            "current_revenue": float(monthly_revenue.iloc[-1]),
            "previous_revenue": None,
        }

    current_period = monthly_revenue.index[-1]
    previous_period = monthly_revenue.index[-2]
    current_revenue = float(monthly_revenue.iloc[-1])
    previous_revenue = float(monthly_revenue.iloc[-2])
    growth_rate = (
        None
        if previous_revenue == 0
        else ((current_revenue - previous_revenue) / previous_revenue) * 100
    )

    return {
        "growth_rate": growth_rate,
        "current_period": str(current_period),
        "previous_period": str(previous_period),
        "current_revenue": current_revenue,
        "previous_revenue": previous_revenue,
    }


def calculate_kpis(data: pd.DataFrame) -> dict[str, Any]:
    """Calculate every Phase 2 KPI and return one reusable result dictionary."""
    if data.empty:
        raise ValueError("KPI calculations require at least one cleaned sales row.")

    validate_kpi_columns(data)
    growth = calculate_monthly_growth(data)
    return {
        "revenue": calculate_revenue(data),
        "profit": calculate_profit(data),
        "profit_margin": calculate_profit_margin(data),
        "average_order_value": calculate_average_order_value(data),
        "orders": calculate_orders(data),
        "customers": calculate_customers(data),
        "growth_rate": growth["growth_rate"],
        "growth_current_period": growth["current_period"],
        "growth_previous_period": growth["previous_period"],
        "growth_current_revenue": growth["current_revenue"],
        "growth_previous_revenue": growth["previous_revenue"],
    }


def kpis_to_dataframe(kpis: dict[str, Any]) -> pd.DataFrame:
    """Convert KPI results into a display-friendly table."""
    rows = [
        {"KPI": "Revenue", "Value": kpis["revenue"], "Unit": "currency"},
        {"KPI": "Profit", "Value": kpis["profit"], "Unit": "currency"},
        {"KPI": "Profit Margin", "Value": kpis["profit_margin"], "Unit": "percent"},
        {
            "KPI": "Average Order Value",
            "Value": kpis["average_order_value"],
            "Unit": "currency",
        },
        {"KPI": "Orders", "Value": kpis["orders"], "Unit": "count"},
        {"KPI": "Customers", "Value": kpis["customers"], "Unit": "count"},
        {
            "KPI": "Monthly Growth Rate",
            "Value": kpis["growth_rate"],
            "Unit": "percent",
        },
    ]
    return pd.DataFrame(rows)
